name=input('Digite o nome do funcionário: ')
company=input('Digite o nome da empresa: ')
qtdeFuncionarios=int(input('Digite a quantidade de funcionários: '))
mediaMensalidade=float(input('Digite a média da mensalidade: '))

print(name + ' trabalha na empresa ' + company)
print('Possui: ', qtdeFuncionarios, ' funcionários.')
print('A média da mensalidade é de: ' + str(mediaMensalidade))
print('=============Verifique os tipos de dados abaixo=============')
print('O tipo de dado da variável [name] é: ', type(name))
print('O tipo de dado da variável [company] é: ', type(company))
print('O tipo de dado da variável [qtdeFuncionarios] é: ', type(qtdeFuncionarios))
print('O tipo de dado da variável [mediaMensalidade] é: ', type(mediaMensalidade))